#!/usr/bin/env python3

import re
from collections import defaultdict, Counter
from typing import Dict

# --------------------------------------------------
def main():
    dna = '''
    GAACTCCAAAAATGAAAACATAGTAGCAATCAAAGCATCCCACTATTTTTTGTCTCTCGTTTCATTAGC
    GTTGTAAATTACTGATACCCTACTATACCTCTACAAGGCCTTTGTCATCTTTTTACTCAAGTGTGAAAT
    CATCACTTATTGTATGAAGGATGAGCTTTCCGTTCGCTAGTTTGCTGAAAAGGCCTTCTGCAATAAGCT
    CTCTATTATCTTTAAAAAAACCTGGTTCCTGGTCTTCCATTCTGCTAAAAGCTGTAGGGGTTTTATCAC
    GAGATTCCCGTTGGCATTCTGACTTATTAAAAATGCTTACAGAAGAAATGGATTCTTTAAATGGTCAAA
    TTAATACGTGGACAGATAATAATCCTTTATTAGATGAAATTACGAAGCCATACAGAAAATCTTCAACTC
    GTTTTTTTCATCCGCTTCTTGTACTTCTAATGTCTAGAGCATCAGTAAATGGGGATCCACCGAGTCAGC
    AACTATTTCAAAGGTACAAACAACTTGCCCGTGTAACAGAATTGATTCATGCTGCCAATATAATTCATA
    TTAATATTGGAGAAGAACAAAGCAACGAACAGATTAAACTTGCAACGTTGGTTGGAGATTATTTACTCG
    GAAAGGCGTCTGTTGATTTAGCACATTTAGAAAACAACGCTATTACAGAAATTATGGCTTCTGTTATTG
    CAAACTTAGTTGAAGGGCACTTCGGAAGCCGACAAAATGGCTCTGTTGGTTTGTCAAACGAACGAACCA
    TCCTTCTGCAATCAGCCTTTATGCCAGCAAAGGCATGTTTATGCGCAAGCATATTGAATAACTCATCAC
    AATACATTAATGATGCGTGTTTCAATTATGGAAAATTTCTAGGCTTATCGCTGCAACTGGCCCATAAGC
    CTGTATCTCCTGACGCCCAAGTTTTGCAAAAGAATAATGACATTTTGAAAACATATGTTGAGAATGCCA
    AGAGCTCATTGTCTGTTTTCCCCGATATAGAGGCTAAGCAAGCTCTCATGGAAATCGCTAATAGTGTTT
    CGAAGTAATCGACAGGTATTGTATCCTGGATTAATATTAGGGTGGCTCATGCATGCTCGTGCAATCGTA
    ACAAATATGTCTTTCTTTTACGAATTTTAACGCTTCAATATAAATCATATTTTTCCTCA
    '''
    dna = re.sub(r'\s+', '', dna)
    print(set(dna))

    counts = {}
    for base in dna:
        if base not in counts:
            counts[base] = 0
        counts[base] += 1
        
    print(f"Dict       : {counts}")

    counts_dd = defaultdict(int)
    for base in dna:
        counts_dd[base] += 1
        
    print(f"DefaultDict: {counts_dd}")

    counts_counter = Counter(dna)
    print(f"Counter    : {counts_dd}")

    print(f"Percent GC : {gc(counts_counter):.02f}%")


# --------------------------------------------------
def gc(freq: Dict[str, int]) -> float:
    total = sum(freq.values())
    return (100 * (freq.get('G', 0) + freq.get('C', 0))) / total \
        if total > 0 else 0.


# --------------------------------------------------
if __name__ == '__main__':
    main()
