#!env/bin/bash python3

#Problem set 10, number 1
#Create a function to format a string of DNA so that each line is no more than 60 nt long. Your function will:
# INPUT: a string of DNA without newlines
# OUTPUT: a string of DNA with lines no more than 60 nucleoties long
dna = 'GATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGGACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACGCTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATGCCAGAGGCTGCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCTACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCCCTGTCATCTTCT'
list_lines = []
def sixty_per_line(DNA_string):
    n = 0
    length_DNA = len(DNA_string)
    while n < length_DNA:
        list_lines.append(DNA_string[n:n+60])
        n = n + 61
    return list_lines
sixty_per_line(dna)
for elem in list_lines:
    print(elem)